// src/components/misc/TimelineProgress.jsx
"use client";
import { useEffect, useRef, useState } from "react";

const MS_PER_DAY = 24 * 60 * 60 * 1000;
const UPDATE_INTERVAL = 10;
const ANIMATION_DURATION = 5000;

function calculateProgress() {
	const now = new Date();
	const curYear = now.getFullYear();

	const startY = new Date(curYear, 0, 1).getTime();
	const endY = new Date(curYear + 1, 0, 1).getTime();
	const yProg = ((now.getTime() - startY) / (endY - startY)) * 100;

	const startD = new Date(curYear, now.getMonth(), now.getDate()).getTime();
	const endD = new Date(curYear, now.getMonth(), now.getDate() + 1).getTime();
	const dProg = ((now.getTime() - startD) / (endD - startD)) * 100;

	const dayOfYear =
		Math.floor(
			(Date.UTC(curYear, now.getMonth(), now.getDate()) -
				Date.UTC(curYear, 0, 1)) /
				MS_PER_DAY,
		) + 1;

	const centuryStart = new Date(2000, 0, 1).getTime();
	const centuryEnd = new Date(2100, 0, 1).getTime();
	const centuryProg =
		((now.getTime() - centuryStart) / (centuryEnd - centuryStart)) * 100;

	return { yProg, dProg, dayOfYear, curYear, centuryProg, now };
}

function formatPercent(v) {
	return Number.isFinite(v) ? v.toFixed(5) + "%" : "0.00000%";
}

export default function TimelineProgress() {
	const loveStartDate = null;

	const [yProg, setYProg] = useState(0);
	const [dProg, setDProg] = useState(0);
	const [dayOfYear, setDayOfYear] = useState(0);
	const [curYear, setCurYear] = useState(new Date().getFullYear());
	const [centuryProg, setCenturyProg] = useState(0);
	const [loveDays, setLoveDays] = useState(0);

	const animYProg = useRef(null);
	const animDProg = useRef(null);
	const animDayOfYear = useRef(null);
	const animCurYear = useRef(null);
	const animCenturyProg = useRef(null);
	const animLoveDays = useRef(null);

	const [, forceUpdate] = useState({});

	function animateValue(ref, targetValue, duration, callback) {
		const startValue = ref.current ?? 0;
		const startTime = performance.now();

		function step(time) {
			const elapsed = time - startTime;
			if (elapsed >= duration) {
				ref.current = targetValue;
				forceUpdate({});
				if (callback) callback();
				return;
			}
			const progress = elapsed / duration;
			ref.current = startValue + (targetValue - startValue) * progress;
			forceUpdate({});
			requestAnimationFrame(step);
		}

		requestAnimationFrame(step);
	}

	useEffect(() => {
		const { yProg, dProg, dayOfYear, curYear, centuryProg, now } =
			calculateProgress();

		animateValue(
			animYProg,
			yProg,
			ANIMATION_DURATION,
			() => (animYProg.current = null),
		);
		animateValue(
			animDProg,
			dProg,
			ANIMATION_DURATION,
			() => (animDProg.current = null),
		);
		animateValue(
			animDayOfYear,
			dayOfYear,
			ANIMATION_DURATION,
			() => (animDayOfYear.current = null),
		);
		animateValue(
			animCurYear,
			curYear,
			ANIMATION_DURATION,
			() => (animCurYear.current = null),
		);
		animateValue(
			animCenturyProg,
			centuryProg,
			ANIMATION_DURATION,
			() => (animCenturyProg.current = null),
		);

		if (loveStartDate) {
			const loveDaysVal =
				(now.getTime() - loveStartDate.getTime()) / MS_PER_DAY;
			animateValue(
				animLoveDays,
				loveDaysVal,
				ANIMATION_DURATION,
				() => (animLoveDays.current = null),
			);
			setTimeout(() => setLoveDays(loveDaysVal), ANIMATION_DURATION);
		}

		setTimeout(() => {
			setYProg(yProg);
			setDProg(dProg);
			setDayOfYear(dayOfYear);
			setCurYear(curYear);
			setCenturyProg(centuryProg);
		}, ANIMATION_DURATION);

		const interval = setInterval(() => {
			const { yProg, dProg, dayOfYear, curYear, centuryProg, now } =
				calculateProgress();

			setYProg(yProg);
			setDProg(dProg);
			setDayOfYear(dayOfYear);
			setCurYear(curYear);
			setCenturyProg(centuryProg);

			if (loveStartDate) {
				const newLoveDays =
					(now.getTime() - loveStartDate.getTime()) / MS_PER_DAY;
				setLoveDays((prev) =>
					Math.abs(prev - newLoveDays) > 0.0001 ? newLoveDays : prev,
				);
			}
		}, UPDATE_INTERVAL);

		return () => clearInterval(interval);
	}, []);

	const displayYProg = animYProg.current !== null ? animYProg.current : yProg;
	const displayDProg = animDProg.current !== null ? animDProg.current : dProg;
	const displayDayOfYear =
		animDayOfYear.current !== null ? animDayOfYear.current : dayOfYear;
	const displayCurYear =
		animCurYear.current !== null ? animCurYear.current : curYear;
	const displayCenturyProg =
		animCenturyProg.current !== null ? animCenturyProg.current : centuryProg;
	const displayLoveDays =
		animLoveDays.current !== null ? animLoveDays.current : loveDays;

	return (
		<>
			<ul>
				<li>
					Today is{" "}
					<span className="time-number">{Math.round(displayDayOfYear)}</span>{" "}
					day of{" "}
					<span className="time-number">{Math.round(displayCurYear)}</span>
				</li>
				<li>
					Century progress:{" "}
					<span className="time-number">
						{formatPercent(displayCenturyProg)}
					</span>
				</li>
				<li>
					Year progress:{" "}
					<span className="time-number">{formatPercent(displayYProg)}</span>
				</li>
				<li>
					Day progress:{" "}
					<span className="time-number">{formatPercent(displayDProg)}</span>
				</li>
				<hr />
				<center>
					{loveStartDate ? (
						<>
							<span className="time-number">{Math.floor(displayLoveDays)}</span>{" "}
							days painted softly on the canvas of 「时光」🎨
						</>
					) : (
						<>
							<span className="time-number">
								一场未曾落幕的梦，静待与君相逢 💫
							</span>
						</>
					)}
				</center>
			</ul>

			<style jsx>{`
        .time-number {
          display: inline-block;
          font-feature-settings: "tnum";
          font-variant-numeric: tabular-nums;
          font-weight: 600;
          color: var(--primary);
          min-width: 2.5em;
          text-align: center;
        }
      `}</style>
		</>
	);
}

// src/components/misc/TimelineProgress.svelte
<script>
  import { onMount } from "svelte";
  import { Tween } from "svelte/motion";
  import { cubicOut } from "svelte/easing";

  const MS_PER_DAY = 24 * 60 * 60 * 1000;
  const UPDATE_INTERVAL = 10;
  const ANIMATION_DURATION = 5000;

  function calculateProgress() {
    const now = new Date();
    const curYear = now.getFullYear();

    const startY = new Date(curYear, 0, 1).getTime();
    const endY = new Date(curYear + 1, 0, 1).getTime();
    const yProg = ((now.getTime() - startY) / (endY - startY)) * 100;

    const startD = new Date(curYear, now.getMonth(), now.getDate()).getTime();
    const endD = new Date(curYear, now.getMonth(), now.getDate() + 1).getTime();
    const dProg = ((now.getTime() - startD) / (endD - startD)) * 100;

    const dayOfYear =
      Math.floor(
        (Date.UTC(curYear, now.getMonth(), now.getDate()) -
          Date.UTC(curYear, 0, 1)) /
          MS_PER_DAY,
      ) + 1;

    const centuryStart = new Date(2000, 0, 1).getTime();
    const centuryEnd = new Date(2100, 0, 1).getTime();
    const centuryProg =
      ((now.getTime() - centuryStart) / (centuryEnd - centuryStart)) * 100;

    return { yProg, dProg, dayOfYear, curYear, centuryProg, now };
  }

  function formatPercent(v) {
    return Number.isFinite(v) ? `${v.toFixed(5)}%` : "0.00000%";
  }

  const loveStartDate = null;

  const yProg = new Tween(0, {
    duration: ANIMATION_DURATION,
    easing: cubicOut,
  });
  const dProg = new Tween(0, {
    duration: ANIMATION_DURATION,
    easing: cubicOut,
  });
  const dayOfYear = new Tween(0, {
    duration: ANIMATION_DURATION,
    easing: cubicOut,
  });
  const curYear = new Tween(new Date().getFullYear(), {
    duration: ANIMATION_DURATION,
    easing: cubicOut,
  });
  const centuryProg = new Tween(0, {
    duration: ANIMATION_DURATION,
    easing: cubicOut,
  });
  const loveDays = new Tween(0, {
    duration: ANIMATION_DURATION,
    easing: cubicOut,
  });

  onMount(() => {
    const initial = calculateProgress();

    yProg.set(initial.yProg);
    dProg.set(initial.dProg);
    dayOfYear.set(initial.dayOfYear);
    curYear.set(initial.curYear);
    centuryProg.set(initial.centuryProg);

    if (loveStartDate) {
      const loveDaysVal =
        (initial.now.getTime() - loveStartDate.getTime()) / MS_PER_DAY;
      loveDays.set(loveDaysVal);
    }

    const interval = setInterval(() => {
      const current = calculateProgress();
      const options = { duration: 0 };

      yProg.set(current.yProg, options);
      dProg.set(current.dProg, options);
      dayOfYear.set(current.dayOfYear, options);
      curYear.set(current.curYear, options);
      centuryProg.set(current.centuryProg, options);

      if (loveStartDate) {
        const newLoveDays =
          (current.now.getTime() - loveStartDate.getTime()) / MS_PER_DAY;
        loveDays.set(newLoveDays, options);
      }
    }, UPDATE_INTERVAL);

    return () => clearInterval(interval);
  });
</script>

<ul>
  <li>
    Today is <span class="time-number">{Math.round(dayOfYear.current)}</span>
    day of
    <span class="time-number">{Math.round(curYear.current)}</span>
  </li>
  <li>
    Century progress: <span class="time-number"
      >{formatPercent(centuryProg.current)}</span
    >
  </li>
  <li>
    Year progress: <span class="time-number"
      >{formatPercent(yProg.current)}</span
    >
  </li>
  <li>
    Day progress: <span class="time-number">{formatPercent(dProg.current)}</span
    >
  </li>
  <hr />
  <center>
    {#if loveStartDate}
      <span class="time-number">{Math.floor(loveDays.current)}</span> days painted
      softly on the canvas of 「时光」🎨
    {:else}
      <span class="time-number">一场未曾落幕的梦，静待与君相逢 💫</span>
    {/if}
  </center>
</ul>

<style>
  .time-number {
    display: inline-block;
    font-feature-settings: "tnum";
    font-variant-numeric: tabular-nums;
    font-weight: 600;
    color: var(--primary);
    min-width: 2.5em;
    text-align: center;
  }
</style>
